version: "2"

services:
    nginx:
        image: linuxserver/nginx
        container_name: nginx
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ${NGINX_PATH}:/config
        restart: unless-stopped
        ports:
            - 9000:80

    hello1:
        image: nginxdemos/hello
        ports:
            - 8112:80

    hello2:
        image: nginxdemos/hello
        ports:
            - 9002:80
